### ISSUE TITLE
When installing in magento 2.3 i get Argument 1 passed to df_path_is_internal() must be of the type string, null given

### ISSUE THREAD

**Issue by AlaaL** [mage2pro/yandex-kassa#5]
Hello,

When installing the plugin in Magento 2.3 using composer and then executing `bin\magento setup:upgrade` i get this error message:

`Type Error occurred when creating object: Magento\Backend\Model\Session\Interceptor, Argument 1 passed to df_path_is_internal() must be of the type string, null given, called in /home/lelasnet/public_html/vendor/mage2pro/core/Framework/Plugin/Session/SessionManager.php on line 50`

**Comment by AlaaL** [comment]
I fixed the previous error by checking the result of dfa function if null or not
but after that i continued to execute `bin/magento setup:di:compile` and get this error:

`Fatal error: Uncaught Error: Class 'Magento\SampleData\Model\Dependency' not found in /home/lelasinfo/public_html/vendor/mage2pro/core/SampleData/Model/Dependency.php:10
Stack trace:
#0 /home/lelasinfo/public_html/vendor/composer/ClassLoader.php(571): include()
#1 /home/lelasinfo/public_html/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile('/home/lelasinfo...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('Df\\SampleData\\M...')
#3 [internal function]: spl_autoload_call('Df\\SampleData\\M...')
#4 /home/lelasinfo/public_html/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(134): class_exists('Df\\SampleData\\M...')
#5 /home/lelasinfo/public_html/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(117): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->includeClass('Df\\SampleData\\M...', '/home/lelasinfo...')
#6 /home/lelasinfo/public_html/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(87): Magento\Setup\Module\Di\Code\Reader\ClassesSca in /home/lelasinfo/public_html/vendor/mage2pro/core/SampleData/Model/Dependency.php on line 10`
